[package]
name = "revm-delegate"
version = "0.1.0"
edition = "2021"

[dependencies]
delegate-trait.path = "../delegate-trait"
revm-delegate-impl.path = "impl"

revm = "4.0"

[build-dependencies]
delegate-trait.path = "../delegate-trait"

[workspace]
members = ["impl"]
